#제목과 버전 설정
application:
   version : v0.0.1
   title : KIMMINYOUNG

#MyBatis 설정
mybatis:
   mapper-locations: classpath:/sqlmap/sqlmapper_*.xml
   type-aliases-package: com.example.first_spring.vo
#MySQL 접속정보 설정
spring:
   datasource:
      driver-class-name : com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dw?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: bs07360012!
   
